# Generated by Django 2.1 on 2019-02-12 22:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='meeting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('m_date', models.DateField()),
                ('m_time', models.TimeField()),
                ('descript', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='staff_users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=756)),
                ('email_address', models.EmailField(max_length=756)),
                ('admin', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='student_users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('email_address', models.EmailField(max_length=254)),
            ],
        ),
        migrations.AddField(
            model_name='meeting',
            name='lect_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.staff_users'),
        ),
    ]
