# Generated by Django 2.1 on 2019-02-13 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='attended',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
