# Generated by Django 2.1 on 2019-01-04 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20190102_2128'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meeting',
            old_name='date',
            new_name='m_date',
        ),
        migrations.RenameField(
            model_name='meeting',
            old_name='time',
            new_name='m_time',
        ),
        migrations.AlterField(
            model_name='meeting',
            name='attendance',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='lecturer_details',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
