# Generated by Django 2.1 on 2019-02-27 00:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20190227_0030'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meeting',
            name='student_name',
        ),
        migrations.AlterField(
            model_name='meeting',
            name='lect_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='staff_users',
        ),
        migrations.DeleteModel(
            name='student_users',
        ),
    ]
