# Generated by Django 2.1 on 2019-01-04 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20190104_1740'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meeting',
            name='attendance',
        ),
        migrations.RemoveField(
            model_name='meeting',
            name='lecturer_details',
        ),
    ]
