# Generated by Django 2.1 on 2019-01-06 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_auto_20190104_1852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='lect_name',
            field=models.CharField(max_length=100),
        ),
    ]
