# Generated by Django 2.1 on 2019-02-27 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_auto_20190227_0958'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='attended_set',
            field=models.BooleanField(default=False),
        ),
    ]
